version: "3.4"

services:
  apache:
    container_name: laravel_apache
    build: ./docker
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env
      - ./composer.json:/var/www/composer.json
      - ./composer.phar:/var/www/composer.phar
      - ./composer.lock:/var/www/composer.lock
      - ./docker-compose.yml:/var/www/docker-compose.yml
      - ./package.json:/var/www/package.json
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
    ports:
      - "80:80"
    environment:
      APP_ENV: dev
    depends_on:
      - db
      - mailcatcher
    networks:
      - app-network
    tty: true

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: laravel
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    tty: true

  mailcatcher:
    container_name: laravel_mailcatcher
    build:
      context: ./docker/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - app-network
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8004:80
    networks:
      - app-network
    tty: true

volumes:
  app_cache:
  mysql:

networks:
  app-network:
    driver: bridge
